[WIP] Add more flexibility in the `client_keys` passed to `asyncssh.connect`
AgnostiqHQ/covalent-slurm-plugin pull request #47
Opened 2023-04-24 02:51 UTC by arosen93

This is an attempt to address #45. Still a WIP.

- [ ] I have added the tests to cover my changes.
- [ ] I have updated the documentation, VERSION, and CHANGELOG accordingly.
- [ ] I have read the CONTRIBUTING document.

2023-04-24 02:51 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/AgnostiqHQ/covalent-slurm-plugin?pullRequest=47) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/AgnostiqHQ/covalent-slurm-plugin?pullRequest=47) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/AgnostiqHQ/covalent-slurm-plugin?pullRequest=47) it.</sub>

2023-04-29 16:30 UTC, wjcunningham7 requested changes
You'll need to adjust the unit tests as well since we check for the existence of the SSH key file.  This can be done through mocking or simply by creating/deleting an empty file in the unit test.

2023-04-29 16:30 UTC, wjcunningham7 commented on CHANGELOG.md
> +## [0.9.0] - 2023-04-23
This header change is not needed; the CI will auto-generate it.  The "Added" and "Changed" blocks are sufficient.

2023-04-29 16:30 UTC, wjcunningham7 commented on CHANGELOG.md
> +### Operations
This change isn't needed, it will get picked up by CI.

2023-04-29 20:32 UTC, arosen93 commented
Thanks, @wjcunningham7! I'll address that shortly and let you know when I'm done.

Do you think it might make this PR easier if #41 is merged first? Not sure which would prevent the most merge conflicts. I'm happy to address any that arise here.

2023-04-30 02:15 UTC, arosen93 commented
@wjcunningham7 --- Alright! I added the necessary tests and everything passes locally.

2023-04-30 13:29 UTC, wjcunningham7 requested changes

2023-04-30 13:29 UTC, wjcunningham7 commented on VERSION
> +0.9.0
Last change needed -- just revert the edits in this file.  It will also be auto-incremented based on your CHANGELOG entries.

Great work @arosen93!

2023-04-30 14:13 UTC, arosen93 commented
@wjcunningham7 --- alright, should be ready to merge! Thanks for the help.

2023-04-30 14:19 UTC, merged